name: Build AdTech Digest

on:
  schedule:
    - cron: '5 1 * * *'  # Runs 09:05 SGT daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python agent.py
      - name: Commit digest
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add output/digest.md
          git commit -m "Update digest [skip ci]" || echo "No changes"
          git push
